version: "3.9"
services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database:/var/lib/mysql
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: database
    depends_on:
      - database