/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./src/**/*.{js,jsx,ts,tsx}', './App.tsx', './Main.tsx'],
	theme: {
		extend: {
			colors: {
				'primary-50': '#EFF6FF',
				'secondary-50': '#73B6FF',
				'secondary-100': '#5595E7',
				'secondary-500': '#2254B5',
				'secondary-700': '#0C2C7E',
				'accent-100': '#FFDAB9',
				'accent-300': '#FFC997',
				'accent-500': '#FFB875',
				'accent-700': '#FFA653',
				'success-50': '#A8D99C',
				'success-300': '#70B464',
				'success-500': '#10652F',
				'error-50': '#FFB4AD',
				'error-200': '#E17F79',
				'error-500': '#A12121',
				'neutral-50': '#FFFFFF',
				'neutral-500': '#A7A7A7',
				'neutral-700': '#0A0A0A',
				'secondary-neutral-50': '#F4F1F1',
				'secondary-neutral-300': '#D5D9DD',
				'secondary-neutral-600': '#BCBCBC',
				'secondary-neutral-700': '#95989C',
			},
			fontFamily: {
				'merriweather-black': ['Merriweather-Black'],
				'merriweather-black-italic': ['Merriweather-BlackItalic'],
				'merriweather-bold': ['Merriweather-Bold'],
				'merriweather-bold-italic': ['Merriweather-BoldItalic'],
				'merriweather-italic': ['Merriweather-Italic'],
				'merriweather-light': ['Merriweather-Light'],
				'merriweather-light-italic': ['Merriweather-LightItalic'],
				'merriweather-regular': ['Merriweather-Regular'],
				'quicksand-bold': ['Quicksand-Bold'],
				'quicksand-light': ['Quicksand-Light'],
				'quicksand-medium': ['Quicksand-Medium'],
				'quicksand-regular': ['Quicksand-Regular'],
				'quicksand-semi-bold': ['Quicksand-SemiBold'],
			},
		},
	},
	plugins: [],
};
