const SUCCESS_DELAY: number = 2000;
const ERROR_MESSAGE_TIMEOUT: number = 5000;
const LONG_ERROR_MESSAGE_TIMEOUT: number = 10000;

export default {
	SUCCESS_DELAY,
	ERROR_MESSAGE_TIMEOUT,
	LONG_ERROR_MESSAGE_TIMEOUT,
};
